/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    editors: EditorAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    presidents: President;
    'board-members': BoardMember;
    'committee-chairs': CommitteeChair;
    'areas-of-focus': AreasOfFocus;
    media: Media;
    editors: Editor;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    presidents: PresidentsSelect<false> | PresidentsSelect<true>;
    'board-members': BoardMembersSelect<false> | BoardMembersSelect<true>;
    'committee-chairs': CommitteeChairsSelect<false> | CommitteeChairsSelect<true>;
    'areas-of-focus': AreasOfFocusSelect<false> | AreasOfFocusSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    editors: EditorsSelect<false> | EditorsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('tr' | 'en') | ('tr' | 'en')[];
  globals: {};
  globalsSelect: {};
  locale: 'tr' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: Editor;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface EditorAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Pages built from the site's sections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Sekmede ve arama sonuçlarında görünen başlık.
   */
  title: string;
  /**
   * Dil kodundan sonraki adres — "projeler" -> /tr/projeler. "home" ana sayfadır; adresini değiştirmeyin.
   */
  path: string;
  /**
   * Arama sonuçlarındaki özet. Boş bırakılabilir.
   */
  description?: string | null;
  /**
   * Bağlantı paylaşıldığında görünen görsel. 1200×630 piksel önerilir. Boşsa kulüp logosu kullanılır.
   */
  ogImage?: (number | null) | Media;
  /**
   * Yalnızca paylaşım kartında kullanılacak başlık. Türkçede boşsa sayfa başlığı kullanılır. İngilizcede boşsa Türkçe karşılığı kullanılır — İngilizce kartta Türkçe başlık istemiyorsanız burayı da doldurun.
   */
  ogTitle?: string | null;
  /**
   * Paylaşım kartındaki özet. Türkçede boşsa yukarıdaki özet kullanılır; İngilizcede boşsa Türkçe karşılığı kullanılır.
   */
  ogDescription?: string | null;
  /**
   * İşaretlenirse arama motorlarına bu sayfayı listelememeleri söylenir. Site haritasından ve /llms.txt'ten de çıkarılır. Sayfa yine de adresi bilen herkese açıktır — bu bir gizlilik ayarı değildir.
   */
  noindex?: boolean | null;
  /**
   * Sayfanın bölümleri, yukarıdan aşağıya. Sürükleyerek sırayı değiştirin.
   */
  layout: (
    | HeroBlock
    | MarqueeBlock
    | AboutBlock
    | NumbersBlock
    | FourWayTestBlock
    | PresidentsMessageBlock
    | PastPresidentsBlock
    | BoardBlock
    | CommitteesBlock
    | AreasOfFocusBlock
    | JoinBlock
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * Portraits. Uploaded once, then chosen on a board member or a chair.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Görme engelli ziyaretçiler için açıklama. Portreler için boş bırakın — kişinin adından üretilir. Logo gibi kendi başına anlam taşıyan görsellerde doldurun.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    portrait?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Kulüp logosu. Her dilin kendi dosyası vardır; İngilizce sayfa İngilizce kilidi kullanır. Alternatif metin görselin kendi kaydından gelir.
   */
  wordmark: number | Media;
  /**
   * Üst çizginin solu — bölge, grup.
   */
  datelineLeft: string;
  /**
   * Üst çizginin sağı — yer ve yıl. Geniş ekranlarda görünür.
   */
  datelineRight?: string | null;
  /**
   * Sayfanın gizli H1'i. Ekranda görünmez; ekran okuyucular ve arama motorları okur.
   */
  srTitle: string;
  /**
   * Büyük cümlenin düz kısmı.
   */
  taglineLead: string;
  /**
   * Cümleyi bitiren, kırmızı dizilen kısım.
   */
  taglineAccent: string;
  /**
   * Butonun yanındaki toplantı notu.
   */
  meetingNote?: string | null;
  /**
   * Buton yazısı.
   */
  cta: string;
  /**
   * Butonun hedefi. "#join" aynı sayfadaki Bize Katıl bölümüne iner — o bölüm sayfada yoksa başka bir adres verin.
   */
  ctaHref: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MarqueeBlock".
 */
export interface MarqueeBlock {
  /**
   * Şeritte dönen kelimeler, sırayla. Kısa tutun — hepsi tek satırda akar.
   */
  items: {
    text: string;
    id?: string | null;
  }[];
  /**
   * İfadeleri ayıran işaret. Boş bırakılırsa yalnızca boşluk kalır.
   */
  separator?: string | null;
  /**
   * Şeridin bir turu kaç saniye sürsün. Büyük sayı daha yavaş demektir.
   */
  speedSeconds: number;
  id?: string | null;
  blockName?: string | null;
  blockType: 'marquee';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBlock".
 */
export interface AboutBlock {
  /**
   * Bölüm numarası — "01".
   */
  index: string;
  /**
   * Numaranın yanındaki başlık.
   */
  label: string;
  /**
   * Sağdaki künye satırı — yer, tarih.
   */
  meta?: string | null;
  /**
   * Arkadaki dev filigran. Tek kelime olmalı.
   */
  watermark: string;
  /**
   * Bölümün büyük puntolu cümlesi.
   */
  heading: string;
  /**
   * Alt sıradaki sütunlar. Üçü bir satıra sığar.
   */
  pillars: {
    /**
     * Sıra numarası — "01". Diller arasında ortaktır.
     */
    n: string;
    title: string;
    body: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'about';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NumbersBlock".
 */
export interface NumbersBlock {
  /**
   * Bölümün üstündeki küçük başlık.
   */
  eyebrow: string;
  /**
   * Rakamlar, soldan sağa. Üçü bir satıra sığar.
   */
  stats: {
    /**
     * Büyük punto rakam — "1000+".
     */
    big: string;
    /**
     * Rakamın altındaki açıklama.
     */
    label: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'numbers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FourWayTestBlock".
 */
export interface FourWayTestBlock {
  /**
   * Sol üstteki bölüm başlığı.
   */
  eyebrow: string;
  /**
   * Sağ üstteki künye satırı.
   */
  meta?: string | null;
  /**
   * Dört soruyu açan cümle.
   */
  heading: string;
  /**
   * Dördü de zorunludur ve sırası sabittir — I, II, III, IV bu sıradan gelir.
   */
  items: {
    /**
     * Sorunun kendisi.
     */
    q: string;
    /**
     * Kulübün bu soruya verdiği karşılık.
     */
    a: string;
    /**
     * Yuvarlak mühürdeki tek kelime. Kısa tutun — dar bir daire.
     */
    stamp: string;
    id?: string | null;
  }[];
  /**
   * Bölümü kapatan alt satır.
   */
  colophon?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'four-way-test';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PresidentsMessageBlock".
 */
export interface PresidentsMessageBlock {
  /**
   * Bölüm başlığı.
   */
  eyebrow: string;
  /**
   * Arkadaki dev filigran. Tek kelime.
   */
  watermark: string;
  /**
   * Büyük puntolu başlık.
   */
  heading: string;
  /**
   * Sol kenarda dik duran satır. Geniş ekranlarda görünür.
   */
  marginDateline?: string | null;
  /**
   * Başkanın portresi. Tek bir görsel — iki dilde de aynı kişi. Alternatif metin görselin kendi kaydından gelir.
   */
  portrait: number | Media;
  /**
   * Dönen mühürdeki yazı. Daire boyunca tekrarlanır; baştaki ve sondaki boşlukları koruyun.
   */
  sealText: string;
  /**
   * Selamlama. Her satır ayrı bir satır olarak dizilir.
   */
  salutation: string;
  /**
   * Alıntıdan önceki paragraflar. İlkinin ilk harfi büyük dizilir.
   */
  openingParagraphs: {
    text: string;
    id?: string | null;
  }[];
  /**
   * Mektubun ortasına taşan alıntı. Tırnakları siz koyun.
   */
  pullQuote: string;
  /**
   * Alıntıdan sonraki paragraflar.
   */
  closingParagraphs: {
    text: string;
    id?: string | null;
  }[];
  /**
   * Mektubu kapatan, büyük dizilen cümle.
   */
  valediction: string;
  /**
   * "Sevgi ve saygılarımla," gibi.
   */
  signOff: string;
  /**
   * İmzanın altında, adın yanında duran satır. Ad buraya yazılmaz — başkanlar listesinden gelir.
   */
  signatureCredit: string;
  /**
   * Bölümü kapatan kayan şeritteki ifadeler.
   */
  manifesto: {
    text: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'presidents-message';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PastPresidentsBlock".
 */
export interface PastPresidentsBlock {
  /**
   * Bölüm numarası — "04".
   */
  index: string;
  /**
   * Numaranın yanındaki başlık.
   */
  label: string;
  /**
   * Bölümün büyük puntolu cümlesi.
   */
  heading: string;
  /**
   * Tüm başkanlar sayfasına giden bağlantının yazısı.
   */
  seeAll: string;
  /**
   * Kaç geçmiş dönem listelensin. Tamamı için Tüm başkanlar sayfası var — telefonda uzun bir liste bu bölümü boğar.
   */
  shown: number;
  id?: string | null;
  blockName?: string | null;
  blockType: 'past-presidents';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BoardBlock".
 */
export interface BoardBlock {
  /**
   * Bölüm başlığı.
   */
  eyebrow: string;
  /**
   * Büyük puntolu başlık.
   */
  heading: string;
  /**
   * Başlığın altındaki giriş cümlesi.
   */
  intro: string;
  /**
   * Çarkın ortasındaki yazı. Altındaki dönem başkanlar listesinden gelir.
   */
  centreLabel: string;
  /**
   * Dönen okun üstündeki yazı.
   */
  arrowLabel: string;
  /**
   * Portrelerin alternatif metni. {name} yazdığınız yere kişinin adı gelir — bu işareti silmeyin.
   */
  portraitAlt: string;
  /**
   * Geri düğmesi.
   */
  prevLabel: string;
  /**
   * İleri düğmesi.
   */
  nextLabel: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'board';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CommitteesBlock".
 */
export interface CommitteesBlock {
  /**
   * Bölüm başlığı.
   */
  eyebrow: string;
  /**
   * Büyük puntolu başlık.
   */
  heading: string;
  /**
   * Başlığın altındaki giriş cümlesi.
   */
  intro: string;
  /**
   * Portrelerin alternatif metni — ekran okuyucular okur. {name} yazdığınız yere kişinin adı gelir; bu işareti silmeyin.
   */
  portraitAlt: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'committees';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AreasOfFocusBlock".
 */
export interface AreasOfFocusBlock {
  /**
   * Bölüm numarası — "07".
   */
  index: string;
  /**
   * Numaranın yanındaki başlık.
   */
  label: string;
  /**
   * Sağdaki künye — programın diğer dildeki adı.
   */
  meta?: string | null;
  /**
   * Künyenin hangi dilde yazıldığı. Büyük harfe çevirmeyi etkiler.
   */
  altLang: 'tr' | 'en';
  /**
   * Bölümün büyük puntolu cümlesi.
   */
  heading: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'areas-of-focus';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "JoinBlock".
 */
export interface JoinBlock {
  /**
   * Bölüm başlığı.
   */
  eyebrow: string;
  /**
   * Arkadaki dev filigran. Tek kelime olmalı.
   */
  watermark: string;
  /**
   * Büyük puntolu çağrı.
   */
  heading: string;
  /**
   * Çağrının altındaki açıklama.
   */
  body: string;
  /**
   * Yazışma adresi. Değiştirirseniz i18n/dictionaries içindeki contact.email de değişmeli — üst menü oradan okur.
   */
  email: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'join';
}
/**
 * Every term the club has had, from its founding to now.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "presidents".
 */
export interface President {
  id: number;
  /**
   * Rotary yılı, en-tire ile: "2026–27". Bir dönemi iki kişi paylaştıysa aynı dönemi iki kayıtta kullanabilirsiniz.
   */
  term: string;
  /**
   * Ad Soyad.
   */
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * The board — the wheel on the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-members".
 */
export interface BoardMember {
  id: number;
  name: string;
  /**
   * Görev adı çeviri dosyalarından gelir.
   */
  role: 'president' | 'vicePresident' | 'secretary' | 'treasurer' | 'pastPresident';
  photo?: (number | null) | Media;
  /**
   * Çarkta saat on ikiden başlayarak sıra.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * The committee chairs — the accordion on the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "committee-chairs".
 */
export interface CommitteeChair {
  id: number;
  name: string;
  /**
   * Komite adı çeviri dosyalarından gelir.
   */
  role: 'club' | 'community' | 'vocational' | 'international' | 'publicImage' | 'foundation' | 'technology';
  photo?: (number | null) | Media;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Rotary's seven areas of focus.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "areas-of-focus".
 */
export interface AreasOfFocus {
  id: number;
  /**
   * Sıralamayı bu anahtar belirler; değiştirilmez.
   */
  key: 'peace' | 'disease' | 'water' | 'maternal' | 'education' | 'economy' | 'environment';
  title: string;
  body: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Who can sign in here. No account here reaches the members area.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "editors".
 */
export interface Editor {
  id: number;
  /**
   * Panelde ve içerik geçmişinde görünen ad.
   */
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'editors';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'presidents';
        value: number | President;
      } | null)
    | ({
        relationTo: 'board-members';
        value: number | BoardMember;
      } | null)
    | ({
        relationTo: 'committee-chairs';
        value: number | CommitteeChair;
      } | null)
    | ({
        relationTo: 'areas-of-focus';
        value: number | AreasOfFocus;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'editors';
        value: number | Editor;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'editors';
    value: number | Editor;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'editors';
    value: number | Editor;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  path?: T;
  description?: T;
  ogImage?: T;
  ogTitle?: T;
  ogDescription?: T;
  noindex?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        marquee?: T | MarqueeBlockSelect<T>;
        about?: T | AboutBlockSelect<T>;
        numbers?: T | NumbersBlockSelect<T>;
        'four-way-test'?: T | FourWayTestBlockSelect<T>;
        'presidents-message'?: T | PresidentsMessageBlockSelect<T>;
        'past-presidents'?: T | PastPresidentsBlockSelect<T>;
        board?: T | BoardBlockSelect<T>;
        committees?: T | CommitteesBlockSelect<T>;
        'areas-of-focus'?: T | AreasOfFocusBlockSelect<T>;
        join?: T | JoinBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  wordmark?: T;
  datelineLeft?: T;
  datelineRight?: T;
  srTitle?: T;
  taglineLead?: T;
  taglineAccent?: T;
  meetingNote?: T;
  cta?: T;
  ctaHref?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MarqueeBlock_select".
 */
export interface MarqueeBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        text?: T;
        id?: T;
      };
  separator?: T;
  speedSeconds?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBlock_select".
 */
export interface AboutBlockSelect<T extends boolean = true> {
  index?: T;
  label?: T;
  meta?: T;
  watermark?: T;
  heading?: T;
  pillars?:
    | T
    | {
        n?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NumbersBlock_select".
 */
export interface NumbersBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  stats?:
    | T
    | {
        big?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FourWayTestBlock_select".
 */
export interface FourWayTestBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  meta?: T;
  heading?: T;
  items?:
    | T
    | {
        q?: T;
        a?: T;
        stamp?: T;
        id?: T;
      };
  colophon?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PresidentsMessageBlock_select".
 */
export interface PresidentsMessageBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  watermark?: T;
  heading?: T;
  marginDateline?: T;
  portrait?: T;
  sealText?: T;
  salutation?: T;
  openingParagraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  pullQuote?: T;
  closingParagraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  valediction?: T;
  signOff?: T;
  signatureCredit?: T;
  manifesto?:
    | T
    | {
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PastPresidentsBlock_select".
 */
export interface PastPresidentsBlockSelect<T extends boolean = true> {
  index?: T;
  label?: T;
  heading?: T;
  seeAll?: T;
  shown?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BoardBlock_select".
 */
export interface BoardBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  centreLabel?: T;
  arrowLabel?: T;
  portraitAlt?: T;
  prevLabel?: T;
  nextLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CommitteesBlock_select".
 */
export interface CommitteesBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  portraitAlt?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AreasOfFocusBlock_select".
 */
export interface AreasOfFocusBlockSelect<T extends boolean = true> {
  index?: T;
  label?: T;
  meta?: T;
  altLang?: T;
  heading?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "JoinBlock_select".
 */
export interface JoinBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  watermark?: T;
  heading?: T;
  body?: T;
  email?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "presidents_select".
 */
export interface PresidentsSelect<T extends boolean = true> {
  term?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-members_select".
 */
export interface BoardMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "committee-chairs_select".
 */
export interface CommitteeChairsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "areas-of-focus_select".
 */
export interface AreasOfFocusSelect<T extends boolean = true> {
  key?: T;
  title?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        portrait?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "editors_select".
 */
export interface EditorsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}